CREATE TABLE Customer (Cust_id VARCHAR2(3) PRIMARY KEY,Fname VARCHAR2(20),Lname VARCHAR2(20),Area VARCHAR2(2),Phone NUMBER(7));
CREATE TABLE Movie( Mv_no NUMBER(2) PRIMARY KEY,Cust_id VARCHAR2(3) NOT NULL,Title VARCHAR2(30) NOT NULL,Star VARCHAR2(2) NOT NULL,Price NUMBER(5,2),FOREIGN KEY (Cust_id) REFERENCES Customer(Cust_id),CHECK (Price BETWEEN 100 AND 250));
INSERT INTO Customer VALUES ('A01','Ivan','Ross','SA',6125467);
INSERT INTO Customer VALUES ('A02','Vandana','Ray','MU',5560379);
INSERT INTO Customer VALUES ('A03','Pramada','Jauguste','DA',4560389);
INSERT INTO Customer VALUES ('A04','Basu','Navindi','BA',6125401);
INSERT INTO Customer VALUES ('A05','Ravi','Shridhar','NA',NULL);
INSERT INTO Customer VALUES ('A06','Rukmini','Aiyer','GH',5125274);
INSERT INTO Movie VALUES (1,'A02','Bloody','JC',181);
INSERT INTO Movie VALUES (2,'A04','The Firm','TC',200);
INSERT INTO Movie VALUES (3,'A01','Pretty Woman','RG',151);
INSERT INTO Movie VALUES (4,'A06','Home Alone','MC',150);
INSERT INTO Movie VALUES (5,'A05','The Fugitive','MF',200);
INSERT INTO Movie VALUES (6,'A03','Coma','MD',100);
INSERT INTO Movie VALUES (7,'A02','Dracula','GO',150);
INSERT INTO Movie VALUES (8,'A06','Quick Change','BM',100);
INSERT INTO Movie VALUES (9,'A03','Gone with the Wind','CB',200);
INSERT INTO Movie VALUES (10,'A05','Carry on Doctor','LP',100);
SELECT * FROM Customer;
SELECT * FROM Movie;
INSERT INTO Customer VALUES (NULL,'Test','User','XX',1234567);
INSERT INTO Customer VALUES ('A01','Test','User','XX',1234567);
INSERT INTO Movie VALUES (11,'A10','Test Movie','AB',150);
SELECT Title FROM Movie WHERE Price > 100 AND Price < 200;
SELECT Cust_id FROM Movie WHERE Star IN ('JC','TC','MC');
SELECT * FROM Customer WHERE Area LIKE '%A%';
SELECT Title
FROM Movie WHERE Price <= 180 AND LENGTH(Title) = 6;
SELECT Title,Price AS Original_Price, Price * 1.10 AS Incremented_Price FROM Movie;
SELECT Fname || ' ' || Lname || ' stays in ' || Area || ' and his phone number is ' || Phone || '.' AS Customer_Details FROM Customer;
ALTER TABLE Customer MODIFY Lname VARCHAR2(20) NOT NULL;
SELECT Fname, Lname FROM Customer WHERE Phone IS NULL;
UPDATE Customer SET Phone = 9876543 WHERE Cust_id = 'A05';
SELECT DISTINCT Cust_id FROM Movie;
ALTER TABLE Movie MODIFY Star VARCHAR2(2) NULL;
DELETE FROM Customer WHERE Cust_id = 'A01';
DELETE FROM Movie WHERE Mv_no = 1;
DROP TABLE Customer;
DROP TABLE Movie;
CREATE TABLE Movie( Mv_no NUMBER(2) PRIMARY KEY,Cust_id VARCHAR2(3) NOT NULL,Title VARCHAR2(30) NOT NULL,Star VARCHAR2(2) NOT NULL,Price NUMBER(5,2),FOREIGN KEY (Cust_id) REFERENCES Customer(Cust_id),CHECK (Price BETWEEN 100 AND 250));
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'MOVIE' AND CONSTRAINT_TYPE = 'R';
ALTER TABLE Movie DROP CONSTRAINT SYS_C008327;